[package]
name = "cursormatrix"
version = "0.1.0"
authors = ["yasuyuky <yasuyuki.ymd@gmail.com>"]

[dependencies]
term = "0.4.4"
termios = "0.2.2"
libc = "0.2.17"
lazy_static = "0.2.2"
crossbeam = "0.2"
unicode-width = "0.1.3"
regex = "0.1"
