[package]
name = "cursormatrix"
version = "0.1.0"
authors = ["Yasuyuki YAMADA <yasuyuki.ymd@gmail.com>"]

[dependencies]
term = "0.4.6"
termios = "0.3.0"
libc = "0.2.29"
lazy_static = "0.2.2"
crossbeam = "0.3.0"
unicode-width = "0.1.4"
unicode-normalization = "0.1.5"
